// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulerAPI.DataContext;

#nullable disable

namespace SchedulerAPI.Migrations
{
    [DbContext(typeof(SchedulerContext))]
    [Migration("20250523012118_updateV2.2")]
    partial class updateV22
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchedulerAPI.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateByEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreateByEmail");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.example@gmail.com",
                            Name = "John Doe",
                            Password = "$2a$11$dc7/3OhfDj1DxaWofWX0mOOm75jJbOinhP4srvGlmyMKg/xHDMQb2",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateByEmail = "john.example@gmail.com",
                            Email = "jane.example@gmail.com",
                            Name = "Jane Smith",
                            Password = "$2a$11$dc7/3OhfDj1DxaWofWX0mOOm75jJbOinhP4srvGlmyMKg/xHDMQb2",
                            Role = "Lecturer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
